In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
# !pip install category_encoders

In [15]:
df = pd.read_csv('./data/preprocessed_movies_data.csv')
df.head()

,Title,Year,Duration,MPA,Rating,Votes,budget,grossWorldWide,gross_US_Canada,opening_weekend_Gross,...,writers,stars,genres,countries_origin,filming_locations,production_companies,Languages,nominations,oscars,Category
0,1. Star Wars: Episode III - Revenge of the Sith,2005,140.0,PG-13,7.6,867000.0,113000000.0,850035635.0,380270577.0,108435841.0,...,George Lucas,"Hayden Christensen, Natalie Portman, Ewan Mc...","Action Epic, Adventure Epic, Dark Fantasy, ...","United States, Italy, Switzerland, Thailand...","Mount Etna, Catania, Sicily, Italy","Lucasfilm, Mestiere Cinema, Pandora Films",English,64,1,Epic
1,"2. The Chronicles of Narnia: The Lion, the Wi...",2005,143.0,PG,6.9,438000.0,180000000.0,745013115.0,291710957.0,65556312.0,...,"Ann Peacock, Andrew Adamson, Christopher Markus","Tilda Swinton, Georgie Henley, William Moseley","Fantasy Epic, Supernatural Fantasy, Sword & ...","United Kingdom, United States","Adrspach National Park, Trutnov, Czech Republic","Walt Disney Pictures, Walden Media","English, German, Brazilian Sign Language",46,0,Epic
2,3. Harry Potter and the Goblet of Fire,2005,157.0,PG-13,7.7,705000.0,150000000.0,897468952.0,290469928.0,102685961.0,...,"Steve Kloves, J.K. Rowling","Daniel Radcliffe, Emma Watson, Rupert Grint","Sword & Sorcery, Teen Adventure, Teen Fantas...","United Kingdom, United States","Glenfinnan Viaduct, Fort William, Highland, ...","Warner Bros., Heyday Films, Patalex Productions","English, French, Latin",48,1,Fantasy
3,4. War of the Worlds,2005,117.0,PG-13,6.5,485000.0,132000000.0,603873504.0,234280354.0,64878725.0,...,"Josh Friedman, David Koepp, H.G. Wells","Tom Cruise, Dakota Fanning, Tim Robbins","Action Epic, Adventure Epic, Alien Invasion,...",United States,"JF Kennedy Blvd., Bayonne, New Jersey, USA","Paramount Pictures, Dreamworks Pictures, Amb...",English,49,3,Epic
4,5. King Kong,2005,187.0,PG-13,7.2,455000.0,207000000.0,556906378.0,218080025.0,50130145.0,...,"Fran Walsh, Philippa Boyens, Peter Jackson","Naomi Watts, Jack Black, Adrien Brody","Adventure Epic, Dark Romance, Dinosaur Adven...","United States, New Zealand, Germany","Shelly Bay, Wellington, New Zealand","Universal Pictures, WingNut Films, Big Prima...",English,104,0,Epic

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import category_encoders as ce
df = df.drop(columns=['Languages', 'genres', 'countries_origin', 'filming_locations', 'writers'])

X = df.drop('grossWorldWide', axis=1)
y = df['grossWorldWide']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
c_columns = ['Category', 'directors', 'stars', 'production_companies']

encoder = ce.TargetEncoder(cols=c_columns)
X_train_encoded = encoder.fit_transform(X_train, y_train)
X_test_encoded = encoder.transform(X_test)

print(X_train_encoded.head())

                                          Title  Year  Duration        MPA  \
6135  386. Seondal: The Man Who Sells the River  2016     120.0  Not Rated
5097                        348. God the Father  2014     101.0          R
2530                381. District 13: Ultimatum  2009     101.0          R
9573                              24. The Flash  2023     144.0      PG-13
633                       134. Tristan + Isolde  2006     125.0      PG-13

      Rating     Votes        budget  gross_US_Canada  opening_weekend_Gross  \
6135     6.6     910.0  2.568496e+07          97477.0                36415.0
5097     5.0     711.0  1.040816e+06         113276.0                15037.0
2530     6.5   47000.0  1.200000e+07          36136.0                11870.0
9573     6.6  227000.0  2.000000e+08      108133313.0             55043679.0
633      6.8   55000.0  5.644354e+08       14734633.0              6583135.0

         directors         stars  production_companies  nominations  oscars  \
6135  3.920371e+07  3.920371e+07          3.920371e+07            0       0
5097  3.729431e+07  3.729431e+07          3.729431e+07            0       0
2530  3.911459e+07  3.911459e+07          3.911459e+07            0       0
9573  1.026487e+08  7.259535e+07          7.259535e+07            7       0
633   4.208295e+07  4.092885e+07          4.092885e+07            0       0

          Category
6135  3.088526e+07
5097  2.683357e+06
2530  8.952643e+07
9573  1.161495e+08
633   8.952643e+07